[package]
name = "cookbook"
version = "0.1.0"
authors = ["Roel de Jong <roel@getrodeo.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.5"
serde = { version = "1.0", features = ["derive"] }
